// Contract address - update after deployment
export const CONTRACT_ADDRESS = import.meta.env.VITE_CONTRACT_ADDRESS || '0x0000000000000000000000000000000000000000'

// Minimal ABI for the functions we need
export const DUCKET_ABI = [
  // Read functions
  {
    inputs: [{ name: 'eventId', type: 'uint256' }],
    name: 'events',
    outputs: [
      { name: 'organizer', type: 'address' },
      { name: 'maxResalePercentage', type: 'uint16' },
      { name: 'resaleEnabled', type: 'bool' },
      { name: 'transferEnabled', type: 'bool' },
      { name: 'paused', type: 'bool' },
      { name: 'cancelled', type: 'bool' },
      { name: 'exists', type: 'bool' },
      { name: 'name', type: 'string' },
      { name: 'eventDate', type: 'uint256' },
      { name: 'maxTicketsPerWallet', type: 'uint256' },
      { name: 'totalSupply', type: 'uint256' },
      { name: 'mintedCount', type: 'uint256' },
      { name: 'resaleLockUntil', type: 'uint256' },
      { name: 'createdAt', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    name: 'ticketTiers',
    outputs: [
      { name: 'eventId', type: 'uint256' },
      { name: 'name', type: 'string' },
      { name: 'seatPrefix', type: 'string' },
      { name: 'price', type: 'uint256' },
      { name: 'maxSupply', type: 'uint256' },
      { name: 'minted', type: 'uint256' },
      { name: 'nextSeatIndex', type: 'uint256' },
      { name: 'exists', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'ticketId', type: 'uint256' }],
    name: 'ticketInfos',
    outputs: [
      { name: 'eventId', type: 'uint256' },
      { name: 'tierId', type: 'uint256' },
      { name: 'seatIdentifier', type: 'string' },
      { name: 'originalPrice', type: 'uint256' },
      { name: 'purchaseTimestamp', type: 'uint256' },
      { name: 'originalPurchaser', type: 'address' },
      { name: 'currentOwner', type: 'address' },
      { name: 'exists', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'ticketId', type: 'uint256' }],
    name: 'resaleListings',
    outputs: [
      { name: 'ticketId', type: 'uint256' },
      { name: 'seller', type: 'address' },
      { name: 'price', type: 'uint256' },
      { name: 'active', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'user', type: 'address' },
      { name: 'eventId', type: 'uint256' },
    ],
    name: 'getUserTicketsForEvent',
    outputs: [{ name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'eventId', type: 'uint256' }],
    name: 'getEvent',
    outputs: [
      {
        components: [
          { name: 'organizer', type: 'address' },
          { name: 'maxResalePercentage', type: 'uint16' },
          { name: 'resaleEnabled', type: 'bool' },
          { name: 'transferEnabled', type: 'bool' },
          { name: 'paused', type: 'bool' },
          { name: 'cancelled', type: 'bool' },
          { name: 'exists', type: 'bool' },
          { name: 'name', type: 'string' },
          { name: 'eventDate', type: 'uint256' },
          { name: 'maxTicketsPerWallet', type: 'uint256' },
          { name: 'totalSupply', type: 'uint256' },
          { name: 'mintedCount', type: 'uint256' },
          { name: 'resaleLockUntil', type: 'uint256' },
          { name: 'createdAt', type: 'uint256' },
        ],
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'ticketId', type: 'uint256' }],
    name: 'getTicketInfo',
    outputs: [
      {
        components: [
          { name: 'eventId', type: 'uint256' },
          { name: 'tierId', type: 'uint256' },
          { name: 'seatIdentifier', type: 'string' },
          { name: 'originalPrice', type: 'uint256' },
          { name: 'purchaseTimestamp', type: 'uint256' },
          { name: 'originalPurchaser', type: 'address' },
          { name: 'currentOwner', type: 'address' },
          { name: 'exists', type: 'bool' },
        ],
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  // Write functions
  {
    inputs: [
      { name: 'tokenId', type: 'uint256' },
      { name: 'to', type: 'address' },
      { name: 'quantity', type: 'uint256' },
    ],
    name: 'mintTicket',
    outputs: [{ name: '', type: 'uint256[]' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'ticketId', type: 'uint256' },
      { name: 'price', type: 'uint256' },
    ],
    name: 'listForResale',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'ticketId', type: 'uint256' }],
    name: 'buyResaleTicket',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ name: 'ticketId', type: 'uint256' }],
    name: 'cancelResaleListing',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const
